app/blueprints/book_management/__init__.py
from flask import Blueprint

book_management_bp = Blueprint('book_management', __name__)

from . import routes, models

app/blueprints/book_management/routes.py
from flask import render_template, request, redirect, url_for
from . import book_management_bp
from app.models import db, Book

@book_management_bp.route('/')
def index():
    """
    query
    """
    books = Book.query.all()
    return render_template('book_list.html', books=books)

@book_management_bp.route('/add', methods=['GET', 'POST'])
def add_book():
    """
    add
    """
    if request.method == 'POST':
        title = request.form['title']
        author = request.form['author']
        published_date = request.form['published_date']
        price = request.form['price']
        new_book = Book(title=title, author=author, published_date=published_date, price=price)
        db.session.add(new_book)
        db.session.commit()
        return redirect(url_for('book_management.index'))
    return render_template('book_form.html')

@book_management_bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit_book(id):
    """
    edit
    """
    book = Book.query.get_or_404(id)
    if request.method == 'POST':
        book.title = request.form['title']
        book.author = request.form['author']
        book.published_date = request.form['published_date']
        book.price = request.form['price']
        db.session.commit()
        return redirect(url_for('book_management.index'))
    return render_template('book_form.html', book=book)

@book_management_bp.route('/delete/<int:id>', methods=['POST'])
def delete_book(id):
    """
    delete
    """
    book = Book.query.get_or_404(id)
    db.session.delete(book)
    db.session.commit()
    return redirect(url_for('book_management.index'))

app/blueprints/book_management/templates/book_form.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ book.title if book else 'Add New Book' }}</title>
</head>
<body>
    <h1>{{ 'Edit Book' if book else 'Add New Book' }}</h1>
    <form method="post">
        <label>Title</label>
        <input type="text" name="title" value="{{ book.title if book else '' }}">
        <label>Author</label>
        <input type="text" name="author" value="{{ book.author if book else '' }}">
        <label>Published Date</label>
        <input type="date" name="published_date" value="{{ book.published_date if book else '' }}">
        <label>Price</label>
        <input type="text" name="price" value="{{ book.price if book else '' }}">
        <button type="submit">{{ 'Update' if book else 'Add' }}</button>
    </form>
</body>
</html>

app/blueprints/book_management/templates/book_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Book Management</title>
</head>
<body>
    <h1>Book List</h1>
    <a href="{{ url_for('book_management.add_book') }}">Add New Book</a>
    <ul>
        {% for book in books %}
            <li>{{ book.title }} by {{ book.author }} 
                <a href="{{ url_for('book_management.edit_book', id=book.id) }}">Edit</a>
                <form action="{{ url_for('book_management.delete_book', id=book.id) }}" method="post">
                    <button type="submit">Delete</button>
                </form>
            </li>
        {% endfor %}
    </ul>
</body>
</html>